name: Docker Build

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: 0 12 * * SAT

jobs:
  get-images-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          packages=$(./packages.py)
          echo "Settings packages as: $packages"
          echo "::set-output name=matrix::$packages"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build-containers:
    needs: get-images-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.get-images-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Extract Tags
        id: extract-tags
        run: |
          REPO=$(cut -f1 -d'/' <<< ${{github.repository}})/${{ matrix.image }}
          TAGS="$REPO:latest"
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          fi
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="${TAGS},$REPO:${MAJOR},$REPO:${MINOR}"
          fi
          if [[ ! -z $VERSION ]]; then
            TAGS="${TAGS},$REPO:${VERSION}"
          fi

          TAGS="${TAGS},$REPO:${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.extract-tags.outputs.tags }}
          context: ${{ matrix.image }}
